name: performance_lints
description: Regras de lint para melhorar a performance da aplicação Flutter/Dart.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  custom_lint_builder: ^0.6.4
  analyzer: ^6.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

